# .github/workflows/build-and-publish.yml
name: Build & Publish Launcher

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  GH_TOKEN: ${{ secrets.GHCR_TOKEN_PRIVATE }}

jobs:
  build-and-publish:
    name: Build & Publish (Windows & Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd mythbound-launcher
          npm ci

      - name: Build & Publish ${{ matrix.platform }}
        run: |
          cd mythbound-launcher
          if [ "${{ matrix.platform }}" = "win" ]; then
            npx electron-builder --win nsis-web --publish=always
          else
            npx electron-builder --linux --publish=always
          fi
